name: Actividad Ingesta de Datos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write


    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'
      - name: paso1 - crea entorno virtual
        run: python -m venv venv
      - name: paso2 - activar entorno virtual
        run: ./venv/Scripts/activate   
      - name: paso3 - actualizar pip
        run: pip install --upgrade pip
      - name: paso4 - instalar dependencias
        run: pip install -e .
      - name: paso5 - Ejecutar script ACTIVIADAD 1
        #run: python src/bigdata/ingesta.py
        run: python src/bigdata/ingesta.py      
      - name: paso6 - Ejecutar script ACTIVIDAD 2
        run: python src/bigdata/cleaning.py
      - name: paso7 - Ejecutar script ACTIVIDAD 3
        run: python src/bigdata/transformation.py        


      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: generación informe ingesta datos en base de datos
          commit_user_name: Miguel Angel Leal Beltran [GitHub Actions]
          commit_user_email: miguel.leal@iudigital.edu.co
          commit_author: Miguel Angel Leal Beltran <miguel.leal@iudigital.edu.co>
